"Canada", "United States", "Afghanistan", "Åland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
"Anguilla", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Ascension", "Azerbaijan", "Australia", "Austria",
"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia",
"Bosnia And Herzegovina", "Botswana", "Bouvet Island", "Brazil", "Brunei Darussalam", "Bulgaria", "Burkina Faso",
"Burundi", "Cambodia", "Cameroon", "Canary Islands", "Cape Verde", "Cayman Islands", "Central African Republic",
"Chad", "Chile", "China", "Christmas Island", "Cocos (keeling) Islands", "Colombia", "Comoros", "Conch Republic",
"Congo", "Cook Islands", "Costa Rica", "Côte D'ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark",
"Diego Garcia", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea",
"Eritrea", "Estonia", "Ethiopia", "Falkland Islands (malvinas)", "Faroe Islands", "Fiji", "Finland", "France",
"French Guiana", "French Polynesia", "Gabon", "Gambia", "Germany", "Georgia", "Ghana", "Gibraltar", "Grenada",
"Greece", "Greenland", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-bissau", "Guyana", "Haiti",
"Heard & Mcdonald Islands", "Honduras", "Hong Kong", "Hungary", "India", "Indonesia", "Iraq",
"Iran, Islamic Republic Of", "Ireland", "Iceland", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan",
"Kazakhstan", "Kenya", "Kyrgyzstan", "Kiribati", "Kuwait", "Lao", "Lesotho", "Latvia", "Lebanon", "Liberia",
"Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Madagascar", "Malawi", "Malaysia",
"Maldives", "Mali", "Malta", "Morocco", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte",
"Macedonia (FYROM)", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montserrat", "Mozambique", "Myanmar",
"Namibia", "Nauru", "Nepal", "New Caledonia", "New Zealand", "Neutrale Zone", "Nicaragua", "Netherlands",
"Netherlands Antilles", "Niger", "Nigeria", "Niue", "Northern Mariana Islands", "Norfolk Island", "Norway", "Oman",
"Pakistan", "Palestinian Territory", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
"Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Réunion", "Rwanda", "Romania", "Russian Federation",
"Solomon Islands", "Samoa", "San Marino", "Sao Tome And Principe", "Saudi Arabia", "Sweden", "Switzerland", "Senegal",
"Serbien und Montenegro", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Somalia", "Spain",
"Sri Lanka", "Saint Helena", "Saint Kitts And Nevis", "Saint Lucia", "Saint Pierre And Miquelon",
"Saint Vincent/Grenadines", "South Africa", "Sudan", "South Korea", "Suriname", "Svalbard And Jan Mayen",
"Swaziland", "Syrian Arab Republic", "Tajikistan", "Taiwan", "Tanzania", "Thailand", "Timor-leste", "Togo",
"Tokelau", "Tonga", "Trinidad And Tobago", "Tristan da Cunha", "Tunisia", "Turkey", "Turkmenistan",
"Turks And Caicos Islands", "Tuvalu", "Uganda", "United Arab Emirates", "United Kingdom", "Ukraine", "Uruguay",
"Uzbekistan", "Vanuatu", "Venezuela", "Viet Nam", "US Virgin Islands", "Wallis And Futuna", "Western Sahara", "Yemen",
"Zambia", "Zimbabwe"
